name: any_call
description: AnyCall, invoke with variant arguments.
version: 1.0.0
repository: https://github.com/yangentao/any_call
homepage: https://github.com/yangentao/any_call

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
